### ISSUE TITLE
Why ? 

### ISSUE THREAD

**Issue by josuebrunel** [kounkou/coach#1]
I don't understand

**Comment by kounkou** [comment]
I went from the fact, the bulk of innovations today is coming from the wealthy countries. Nevertheless, in developing countries, things are changing. From the minimal telecom infrastructures burgeoning out there we could build services around. So this API is meant to create those API's.

**Comment by josuebrunel** [comment]
Damn why so philosophical, i was just trolling lol

**Comment by kounkou** [comment]
Such a troll! Wanna be fed? :smile:
